# .github/workflows/deploy.yml
name: Deploy on Tag

on:
  push:
    tags:
      - '*'          # match any single-level tag
      - '*/*'        # also match nested tag names like `releases/1.0.0`

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml

  deploy_wo_prefix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    needs: call-ci
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: tester
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, bioconda
          auto-update-conda: true

      - name: Run deploy script
        shell: bash -l {0}
        run: |
          conda create --yes -n deploytest python=${{ matrix.python-version }} git jupyter
          conda activate deploytest
          bash ./deploy.sh "${{ github.repository }}" "${{ github.ref_name }}"

  deploy_w_prefix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    needs: call-ci
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: tester
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, bioconda
          auto-update-conda: true

      - name: Run deploy script
        shell: bash -l {0}
        run: |
          conda create --yes -n deploytest python=${{ matrix.python-version }} git jupyter
          conda activate deploytest
          bash ./deploy.sh "${{ github.repository }}" "${{ github.ref_name }}" "~/.local"
