name: Metapool CI

# Controls when the action will run.
on:
  # Triggers the workflow on pull request and push events, only on the master
  # branch
  pull_request:
    branches:
      - master
      - beta
  push:
    branches: 
      - master
      - beta

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml